// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfcjeJP969FBxfyPbivqjjeH7uHTWlpno',
    appId: '1:244432064616:web:78a072c7a6786cc832abdd',
    messagingSenderId: '244432064616',
    projectId: 'car-rental-system-6a8f5',
    authDomain: 'car-rental-system-6a8f5.firebaseapp.com',
    storageBucket: 'car-rental-system-6a8f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Oqh9s9I8IhLNGHqpBxy6npdE4D99X8s',
    appId: '1:244432064616:android:2742051ce2168d6132abdd',
    messagingSenderId: '244432064616',
    projectId: 'car-rental-system-6a8f5',
    storageBucket: 'car-rental-system-6a8f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUbZ8Zazles6J_P3nOAmHe-dSu87t0d4',
    appId: '1:244432064616:ios:97c85c63d5e28eeb32abdd',
    messagingSenderId: '244432064616',
    projectId: 'car-rental-system-6a8f5',
    storageBucket: 'car-rental-system-6a8f5.firebasestorage.app',
    androidClientId: '244432064616-7cr5qi11bb441segu0a1pgs158s1bv74.apps.googleusercontent.com',
    iosClientId: '244432064616-2hbdr52ggtj9lnohed3sbdt6t9ok2mvk.apps.googleusercontent.com',
    iosBundleId: 'com.manikadahal.chessgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbUbZ8Zazles6J_P3nOAmHe-dSu87t0d4',
    appId: '1:244432064616:ios:0da008a8d2acea0f32abdd',
    messagingSenderId: '244432064616',
    projectId: 'car-rental-system-6a8f5',
    storageBucket: 'car-rental-system-6a8f5.firebasestorage.app',
    androidClientId: '244432064616-7cr5qi11bb441segu0a1pgs158s1bv74.apps.googleusercontent.com',
    iosClientId: '244432064616-obgn361mr7qckah7amli2iqb2epssnhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessPython',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfcjeJP969FBxfyPbivqjjeH7uHTWlpno',
    appId: '1:244432064616:web:8711d7fbc460c47b32abdd',
    messagingSenderId: '244432064616',
    projectId: 'car-rental-system-6a8f5',
    authDomain: 'car-rental-system-6a8f5.firebaseapp.com',
    storageBucket: 'car-rental-system-6a8f5.firebasestorage.app',
  );
}
